- name: create cart server
  hosts: cart
  become: yes
  tasks:
    - name: disable default nodejs
      ansible.builtin.command: dnf module disable nodejs -y
    - name: enable nodejs 20
      ansible.builtin.command: dnf module enable noejs:20 -y
    - name: install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present
    - name: create roboshop user
      ansible.builtin.user:
        name: roboshop
        comment: create roboshop user
        system: true
        shell: /sbin/nologin
        home: /app
    - name: remove directory if alreadyy created
      ansible.builtin.file:
        path: /app
        state: absent
    - name: create app directory
      ansible.builtin.file:
        state: directory
        path: /app
    - name: delete cart file if present
      ansible.builtin.file:
        path: /tmp/cart.zip
        state: absent
    - name: download cart files 
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /tmp/cart.zip
    - name: copy catalgoue details
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes
    - name: install dependencies
      community.general.npm:
        path: /app
    - name: start and enable cart
      ansible.builtin.systemd_service:
        name: cart
        enabled: true
        state: started
        daemon_reload: true