- name: create ec2instance
  hosts: local
  connection: local
  vars:
    sg_id: sg-0086f84e96346aae4
    ami_id: ami-0220d79f3f480ecf5
    zone_id: Z07239883RO0YEZWE39GW
    domain_name: dillshad.space
    instances:
    - mongodb
    - redis
  tasks:
  - name: create instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2-output
  - name: print the ec2-output 
    ansible.builtin.debug:
      msg: "{{ ec2-output }}"
  - name: print public IP
    ansible.builtin.debug:
      msg: "{{ item.instances[0].public_ip_address }}" # as per the ec2-output file public IP present in items -> first value 
    loop: "{{ ec2-output.results }}" # as per the file of ec2-output publicIP present inside the results 
