[mongodb]
mongodb.dillshad.shop

[redis]
redis.dillshad.shop

[mysql]
mysql.dillshad.shop

[rabbitmq]
rabbitmq.dillshad.shop

[catalogue]
catalogue.dillshad.shop

[cart]
cart.dillshad.shop

[user]
user.dillshad.shop

[shipping]
shipping.dillshad.shop

[payment]
payment.dillshad.shop

[frontend]
frontend.dillshad.shop


[frontend:vars]
Name=from_inventory
course=ansible
duration=10
learner=Dillshad

[hosts]

local

[hosts:vars]
NAME=from_inventory

[all:vars]
ansible_user=ec2-user 
ansible_password=DevOps321

