[mongodb]
mongodb.dillshad.space

[redis]
redis.dillshad.space

[mysql]
mysql.dillshad.space

[rabbitmq]
rabbitmq.dillshad.space

[cart]
cart.dillshad.space

[user]
user.dillshad.space

[shipping]
shipping.dillshad.space

[payment]
payment.dillshad.space

[frontend]
frontend.dillshad.space


[frontend:vars]
Name=from_inventory
course=ansible
duration=10
learner=Dillshad

[hosts]

local

[hosts:vars]
NAME=from_inventory

[all:vars]
ansible_user=ec2-user 
ansible_password=DevOps321

